version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_booking_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "32000:3306"

  adapter:
    image: vldcocos/hotel_booking:adapter
    depends_on:
      - db
    ports:
      - "32500:32500"

  admin_interface:
    image: vldcocos/hotel_booking:admin_interface
    depends_on:
      - adapter
    ports:
      - "32501:32501"

  client_interface:
    image: vldcocos/hotel_booking:client_interface
    depends_on:
      - adapter
    ports:
      - "32502:32502"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    links:
      - db
      - adapter
      - client_interface
      - admin_interface
    depends_on:
      - node-exporter
      - admin_interface
      - client_interface
      - adapter

  node-exporter:
    image: prom/node-exporter
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

volumes:
  db_data: {}
  prometheus_data: {}
