version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_booking
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "32000:3306"

volumes:
  db_data: {}